version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./:/code:delegated
    environment:
      - BUNDLE_PATH=/code/.bundle

  postgres:
    image: postgres:14.9-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
