name: release

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ 'deploy' ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: 1024pix/pix-actions/release@main
        env:
          GITHUB_TOKEN: ${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}
